#=================== Initial Configs ===============#
include:
  - template: SAST.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

#=================== BUILD - Package ===============#
build_package:
    image: node:latest
    stage: build
    only:
      - tags
      - develop
      - merge_requests
    except:
      - /^v.*$/
    cache:
      paths:
      - node_modules/
    script:
      - npm install --unsafe-perm -g vsce
      - npm install --unsafe-perm
      - vsce package -o $CI_PROJECT_NAME-$CI_JOB_ID-$CI_PIPELINE_SOURCE.vsix --baseContentUrl $BASE_CONTENT_URL
    artifacts:
      name: "artifacts-$CI_PROJECT_NAME-$CI_JOB_ID"
      expire_in: 2 weeks
      paths:
        - "*.vsix"

build_package_release:
    image: node:latest
    stage: build
    only:
      - tags
      - /^v.*$/
    except:
      - branches
      - merge_requests
    cache:
      paths:
      - node_modules/
    script:
      - npm install --unsafe-perm -g vsce
      - npm install --unsafe-perm
      - vsce package -o $CI_PROJECT_NAME-$CI_COMMIT_TAG.vsix --baseContentUrl $BASE_CONTENT_URL
    artifacts:
      name: "artifacts-$CI_PROJECT_NAME-$CI_COMMIT_TAG"
      paths:
        - "*.vsix"


#=================== DEPLOY - Package ==============#
deploy_package:
    image: node:latest
    stage: deploy
    only:
      - tags
      - /^v.*$/
    except:
      - branches
      - merge_requests
    variables:
      GIT_STRATEGY: none
    script:
      - npm install --unsafe-perm -g vsce
      - vsce publish -p $VSCE_PERSONAL_ACCESS_TOKEN --packagePath $CI_PROJECT_NAME-$CI_COMMIT_TAG.vsix

#=================== TEST ==========================#
sast:
  only:
    - tags
    - develop
    - merge_requests

license_management:
  only:
    - tags
    - develop
    - merge_requests

dependency_scanning:
  only:
    - tags
    - develop
    - merge_requests

code_quality:
  only:
    - tags
    - develop
    - merge_requests